# Site settings
title: Oops!
email: yxj0207@gmail.com
description: Just another kernel noob's blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://llseek.github.io"
github_username: llseek

# Build settings
markdown: kramdown

# Analytics settings
analytics:
  provider: google
  google:
    tracking_id: 'UA-60893867-1'
